### ISSUE TITLE
bundleExec error

### ISSUE THREAD

**Issue by mkoehler2911** [dwightjack/grunt-premailer#27]
Hi!
I'm using the premailer for my grunt project.
Now, I'd like to use the option.bundle Exec.

My Gruntfile:
premailer: {
         html: {
           options: {
             mode : 'html',
             removeComments: true,
              bundleExec: true
            },
            files: [{
                expand: true,
                src: ['dist/*.html'],
                dest: ''
            }]
          },
          txt: {
            options: {
              mode: 'txt'
            },
            files: [{
                expand: true,
                src: ['dist/*.html'],
                dest: '',
                ext: '.txt'
            }]
          }
        }

I run my grunt and I got these Errors:
Running "premailer:html" (premailer) task
Could not locate Gemfile
Could not locate Gemfile
Could not locate Gemfile
Fatal error: Error

If I delete the line "bundleExec: true" everything works fine.
Any ideas?
Thanks!!!

**Comment by mkoehler2911** [comment]
Solved:
Added  :css_to_attributes => true inside of premailer.rb

**Comment by dwightjack** [comment]
This looks weird. The `bundleExec` option just prepends `bundle exec` to the CLI command.

The error looks like you miss a `Gemfile` on your project which is a required file in order for bulder to work.
