### ISSUE TITLE
Add option for disable useless output 

### ISSUE THREAD

**Issue by hudochenkov** [dwightjack/grunt-premailer#30]
Can you add option for disabling output with client's supported properties, please? It's really annoying and useless. Premailer's authors [planned remove](https://github.com/premailer/premailer/wiki/New-Premailer-2.0-Planning) this “CSS analysis” in Premailer 2.0.

**Comment by dwightjack** [comment]
Hi,

I've pushed a new version ([0.2.13](https://github.com/dwightjack/grunt-premailer/releases/tag/0.2.13)) with a new option [`warnLevel`](https://github.com/dwightjack/grunt-premailer#optionswarnlevel) which maps to premailer levels

**Comment by hudochenkov** [comment]
Thank you very much :)
