### ISSUE TITLE
[ERROR] (node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by lukeruth** [dwightjack/grunt-premailer#35]
```
[INFO] Running "premailer:html" (premailer) task
[ERROR] (node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
[ERROR] Trace
[ERROR]   at Socket.addListener (events.js:179:15)
[ERROR]   at Socket.Readable.on (_stream_readable.js:671:33)
[ERROR]   at Socket.once (events.js:204:8)
[ERROR]   at Socket.Readable.pipe (_stream_readable.js:580:8)
[ERROR]   at /Users/lukeruth/fundrise/fundrise-email/node_modules/grunt-premailer/tasks/premailer.js:114:30
[ERROR]   at /Users/lukeruth/fundrise/fundrise-email/node_modules/grunt-premailer/node_modules/async/lib/async.js:118:13
[ERROR]   at Array.forEach (native)
[ERROR]   at _each (/Users/lukeruth/fundrise/fundrise-email/node_modules/grunt-premailer/node_modules/async/lib/async.js:39:24)
[ERROR]   at Object.async.each (/Users/lukeruth/fundrise/fundrise-email/node_modules/grunt-premailer/node_modules/async/lib/async.js:117:9)
[ERROR]   at Object.<anonymous> (/Users/lukeruth/fundrise/fundrise-email/node_modules/grunt-premailer/tasks/premailer.js:72:15)
[ERROR]   at Object.<anonymous> (/Users/lukeruth/fundrise/fundrise-email/node_modules/grunt/lib/grunt/task.js:264:15)
[ERROR]   at Object.thisTask.fn (/Users/lukeruth/fundrise/fundrise-email/node_modules/grunt/lib/grunt/task.js:82:16)
[ERROR]   at Object.<anonymous> (/Users/lukeruth/fundrise/fundrise-email/node_modules/grunt/lib/util/task.js:301:30)
[ERROR]   at Task.runTaskFn (/Users/lukeruth/fundrise/fundrise-email/node_modules/grunt/lib/util/task.js:251:24)
[ERROR]   at Task.<anonymous> (/Users/lukeruth/fundrise/fundrise-email/node_modules/grunt/lib/util/task.js:300:12)
[ERROR]   at /Users/lukeruth/fundrise/fundrise-email/node_modules/grunt/lib/util/task.js:227:11
[ERROR]   at process._tickCallback (node.js:355:11)
[ERROR] 
```

Thanks for your work - this task is great. For some reason though, I get this error when I run it. It runs to completion and the CSS is correctly inlined but this error makes me wonder what's going on. 

I think it may come from the fact that I'm running it against multiple files in quick succession, but I'm not sure.

**Comment by dwightjack** [comment]
Hi,

yes that could be the case.

How many files do you process? Are they spanned between multiple subtasks?

**Comment by lukeruth** [comment]
Thanks for getting back to me. At this point I'm processing about 25 or so files? I'll be adding to it incrementally though. I'm not sure what you mean when you say "spanned between multiple subtasks". I have one grunt task "premailer" which inlines the CSS for all the HTML files in a given directory. 

Is there some better way I should be splitting that up or pacing them out?

**Comment by dwightjack** [comment]
The issue might arise because you are processing more file than the default eventemitter limit (10 I guess). Still it should be safe since I'm batching it here (https://github.com/dwightjack/grunt-premailer/blob/master/tasks/premailer.js#L110).

Will keep this open and try to lower the batch limit.

Thanks!

**Comment by lukeruth** [comment]
Awesome. Thanks for looking into it. Let me know if you want any help testing this.

**Comment by lukeruth** [comment]
Was this resolved?

**Comment by dwightjack** [comment]
Sorry did some cleanup and ended up closing this issue as well.

I've updated the async version. Let me know if it solved the issue. Other than that the only solution I can think about is adding an option to set the async limit, so that you might limit it on a "per subtask" base.

**Comment by lukeruth** [comment]
Yes! I no longer see the error. Thanks for taking care of this.
