### ISSUE TITLE
duplicated css properties

### ISSUE THREAD

**Issue by marcobiedermann** [dwightjack/grunt-premailer#37]
Adding:
```
td {
  vertical-align: top;
}
```

Should be:
```
<td valign="top">
</td>
```

Instead of:
```
<td style="vertical-align: top" valign="top">
</td>
```

**Comment by dwightjack** [comment]
Hi I think this issue is related to Premailer, so I think it'd be better to post an issue there https://github.com/premailer/premailer/issues
