### ISSUE TITLE
Premailer CSS attributes creates unwanted styles.

### ISSUE THREAD

**Issue by TanKucukhas** [dwightjack/grunt-premailer#38]
If you look at the [premailer documentation](https://github.com/premailer/premailer#premailer-specific-css) it says premailer looks for a few CSS attributes that make working with tables a bit easier.

When I try to use some of the attributes with grunt-premailer however result is this
css:
`table{
-premailer-cellpadding: 0;
-premailer-cellspacing: 0;
}`
result:
`<table style="-premailer-cellpadding: 0; -premailer-cellspacing: 0; " cellpadding="0" cellspacing="0">
`
expected result should be:
`<table cellpadding="0" cellspacing="0">`

**Comment by albell** [comment]
+1

**Comment by samel89** [comment]
I'm not seeing this on the current version (release/1.0.0), however, if only premailer-specific CSS is used then a redundant `style=";"` is generated
