### ISSUE TITLE
[QUESTION] background-image/position/repeat is replaced with background

### ISSUE THREAD

**Issue by marocas** [dwightjack/grunt-premailer#40]
I have this code to make a dashed style on my table, and this is getting replaced with background.
Is there a way that i cant "exclude" inlining on my element?

````
style="background-image: linear-gradient(to right, #abadab 31%, rgba(255,255,255,0) 0%); background-size: 15px 1px; background-repeat: repeat-x; display: block;"
````

**Comment by dwightjack** [comment]
Hi,

I think this is an issue related to premailer. Im not aware of a method to exclude a rule from inlining.
Your best chance is file a new issue on the premailer issue tracker: https://github.com/premailer/premailer/issues

Add a reference to this issue so that I could track it as well.
