### ISSUE TITLE
Replace Hpricot with Nokogiri

### ISSUE THREAD

**Issue by marcobiedermann** [dwightjack/grunt-premailer#41]
Hpricot has ended. Please consider an alternative like nokogiri.

> After years of lack of a proper maintainer for one of why's jewels, it has been decided to finally close the book on hpricot. Most users have migrated to alternatives and there is simply no time or energy to continue with the current codebase.

https://github.com/hpricot/hpricot

Nokogiri:
https://github.com/sparklemotion/nokogiri

**Comment by dwightjack** [comment]
Hi premailer uses either hpricot or nokogiri. I updated the docs suggesting to install nokogiri.

https://github.com/dwightjack/grunt-premailer/releases/tag/1.0.0
